### PR TITLE
Support any case for DTD.

### PR DESCRIPTION
**Pull request by xguerin**

### CODE REVIEW

**Comment by dbuenzli** [comment]
The [annoted XML specification](http://www.xml.com/axml/notes/UCaseKW.html) is quite clear that only uppercase keywords are allowed.

**Comment by xguerin** [comment]
Indeed. Apologies. My background search was not very thorough. 

However, only offering a strict mode prevent the use of your parser with a wide range of HTML5 web pages where such a constraint is not required, including google.com.

Would you consider a flag to authorize a more permissive parsing?

**Comment by dbuenzli** [comment]
`xmlm` is not an HTML parser, it's an XML parser, forget about trying to parse HTML with it, there are many other things that will fail (e.g. [self-closing elements](https://www.w3.org/TR/html/syntax.html#void-elements)) if you try to do so. Use @aantron's [markup.ml](https://github.com/aantron/markup.ml) if you want to parse html.

**Comment by xguerin** [comment]
Thanks for the pointer.

**Pull request closed without merging**
